remote_theme: just-the-docs/just-the-docs

title: Impact of Rising Sea Levels on Coastal Residential Real Estate Assets
baseurl: ""
repository: prarid/SeaLevelRiseImpact_CoastalRealEstate
url: "prarid.github.io/SeaLevelRiseImpact_CoastalRealEstate/"
github_username:  prarid
